### ISSUE TITLE
Legacy job implementation in user-api that should be replaced with argo related logic

### ISSUE THREAD

**Issue by fridex** [thoth-station/management-api#507]
**Describe the feature**

See https://github.com/thoth-station/user-api/issues/965

**Comment by saisankargochhayat** [comment]
Only this end-point, in similar fashion to user-api - `/solver/python/{analysis_id}/status` right?

**Comment by fridex** [comment]
> Only this end-point, in similar fashion to user-api - `/solver/python/{analysis_id}/status` right?

Yes. :+1:
