### ISSUE TITLE
Management-API inputs for solving packages should have optional package version and use latest version of package from a certain index by default unless differently specified

### ISSUE THREAD

**Issue by pacospace** [thoth-station/management-api#611]

**Comment by fridex** [comment]
As of now, we consider "all versions" if no version is specified. Is this related to a problem? "latest" version can be tricky (latest release based on date or latest based on semver?).

**Comment by pacospace** [comment]
> As of now, we consider "all versions" if no version is specified.

> Is this related to a problem?
If you want to solve a specific package that thoth is missing

 "latest" version can be tricky (latest release based on date or latest based on semver?).
Data from PyPI maybe? WDYT?

**Comment by fridex** [comment]
> > As of now, we consider "all versions" if no version is specified.
> 
> > Is this related to a problem?
> > If you want to solve a specific package that thoth is missing
> 
> "latest" version can be tricky (latest release based on date or latest based on semver?).
> Data from PyPI maybe? WDYT?

What's the user story behind this? It will introduce a new code which will need to be maintained. Do we have a need for that?

**Comment by pacospace** [comment]
I think we can close this, no user story for now based on the user of management-api

**Comment by fridex** [comment]
Future ourselves: PyPI is planning to add a "latest package" endpoint.
