### ISSUE TITLE
Management-API inputs for solving packages should give error if a package,version,index is not present on Source

### ISSUE THREAD

**Issue by pacospace** [thoth-station/management-api#612]

**Comment by fridex** [comment]
Which endpoint should provide an error to users?

**Comment by pacospace** [comment]
> Which endpoint should provide an error to users?

I think https://github.com/thoth-station/management-api/blob/7aa47904bd07b139c59d0ec3d0f626b39d7c6703/openapi/openapi.yaml#L29 should stop us from scheduling solver for packages which do not exist on PyPI for example. WDYT?

**Comment by fridex** [comment]
> > Which endpoint should provide an error to users?
> 
> I think
> 
> https://github.com/thoth-station/management-api/blob/7aa47904bd07b139c59d0ec3d0f626b39d7c6703/openapi/openapi.yaml#L29
> 
> should stop us from scheduling solver for packages which do not exist on PyPI for example. WDYT?

Why not keeping this logic in solver? The scheduling part is an async part - I submit a request and the service responds to me. What's the point of having this on the endpoint? Moreover, the same logic is implemented in thoth-solver which already provides this as part of its result.

**Comment by fridex** [comment]
Moreover, it can diverge how the service acts to users. Corner cases, like submitting a request when a package exists but the solver fails because the package was removed while the request has been served will require multiple handling logics on user's side. Also, who is the targetted consumer of these endpoints?

**Comment by pacospace** [comment]
> Moreover, it can diverge how the service acts to users. Corner cases, like submitting a request when a package exists but the solver fails because the package was removed while the request has been served will require multiple handling logics on user's side. Also, who is the targetted consumer of these endpoints?

Isn't the endpoint used by administrators to test some solver package?

**Comment by fridex** [comment]
> > Moreover, it can diverge how the service acts to users. Corner cases, like submitting a request when a package exists but the solver fails because the package was removed while the request has been served will require multiple handling logics on user's side. Also, who is the targetted consumer of these endpoints?
> 
> Isn't the endpoint used by administrators to test some solver package?

If so, I still don't see why this logic should be present on API rather than having the results available after the request is submitted.

**Comment by pacospace** [comment]
> > > Which endpoint should provide an error to users?
> > 
> > 
> > I think
> > https://github.com/thoth-station/management-api/blob/7aa47904bd07b139c59d0ec3d0f626b39d7c6703/openapi/openapi.yaml#L29
> > 
> > should stop us from scheduling solver for packages which do not exist on PyPI for example. WDYT?
> 
> Why not keeping this logic in solver? The scheduling part is an async part - I submit a request and the service responds to me. What's the point of having this on the endpoint? Moreover, the same logic is implemented in thoth-solver which already provides this as part of its result.

I think based on this and what you described, does not make sense indeed. Thanks @fridex
