### ISSUE TITLE
Deliver Container Image

### ISSUE THREAD

**Issue by pacospace** [thoth-station/management-api#636]
Hey, AICoE-CI!

Please build and deliver the following git tag:

Tag: 0.8.2

**Comment by harshad16** [comment]
There is an issue due to change in the aicoe-ci configuration.

**Comment by harshad16** [comment]
Fixing this manually.

**Comment by pacospace** [comment]
> Fixing this manually.

Thanks @harshad16!

**Comment by harshad16** [comment]
Available now : https://quay.io/repository/thoth-station/management-api?tab=tags

**Comment by pacospace** [comment]
> Available now : https://quay.io/repository/thoth-station/management-api?tab=tags

I deployed image in test, but running version I still get:

```
 connection: close 
 content-length: 34 
 content-type: application/json 
 date: Mon30 Nov 2020 13:20:39 GMT 
 server: gunicorn/20.0.4 
 x-management-api-service-version: 0.8.1+storage.0.25.17.common.0.20.4 
 x-management-api-version: 0.8.1
```

**Comment by harshad16** [comment]
Thanks @pacospace , for noticing the issue.
the wrong tag was used to build the image .
it is now fixed and updated in cluster env's.
https://management.stage.thoth-station.ninja/metrics
