### ISSUE TITLE
Deliver Container Image

### ISSUE THREAD

**Issue by fridex** [thoth-station/management-api#713]
Hey, AICoE-CI!

Please build and deliver the following git tag:

Tag: 0.13.0

**Comment by fridex** [comment]
CC @harshad16 PTAL, looks like v0.13.0 was not delivered to quay: https://quay.io/repository/thoth-station/management-api?tab=tags

**Comment by harshad16** [comment]
Thanks frido, i will take a look at this
tag mentioned above should be `Tag: v0.13.0` , as the pipelines will keep looking for 0.13.0
will close this and open another one.

**Comment by fridex** [comment]
Thanks for the clarification and sorry for the confusion :+1:
