### ISSUE TITLE
Management API unable to respond successful

### ISSUE THREAD

**Issue by TomasJani** [thoth-station/management-api#725]
**Describe the bug**
I was not able to create any successful request on Management API (endpoint /dependency-monkey/python/*) on MOC. Every request returned 500 with very little information.

**To Reproduce**
I tried default config from Management MOC /dependency-monkey/python and [this](https://github.com/TomasJani/thoth-issue-predictor/blob/main/thoth_issue_predictor/loader/dm_specifications/specification.json) specification. I did not change any of the query parameters in both cases. 

**Expected behavior**

I got this message:

**500 Error: INTERNAL SERVER ERROR**
```json
{
  "details": {
    "datetime": "2021-03-02T16:35:06.796867",
    "type": "InternalServerError"
  },
  "error": "Internal server error occurred, please contact administrator with provided details."
}
```
on what I think is valid request so I did not expect this :)

**Additional context**
I am not sure if I test this API properly before so I don't know if this is new problem or it never worked.

**Comment by harshad16** [comment]
Thanks for opening the issue.
checking on this.

**Comment by harshad16** [comment]
@TomasJani This issue is now fixed.
Please try it out and gives us feedback.

**Comment by TomasJani** [comment]
500 status code is gone. Thank you very much for such a quick response and fix. I'll look into it more in next couple of days and test it appropriately.

**Comment by harshad16** [comment]
awesome, please let us know if you face any issues.
