### ISSUE TITLE
Management API failing every inspection

### ISSUE THREAD

**Issue by TomasJani** [thoth-station/management-api#736]
**Describe the bug**
I was not able to create any successful request on Management API (endpoint /dependency-monkey/python/*) on MOC. Every request fails immediately after requesting. 

**To Reproduce**
I tried default config from Management MOC /dependency-monkey/python and [this](https://github.com/TomasJani/thoth-issue-predictor/blob/main/thoth_issue_predictor/loader/dm_specifications/specification.json) specification. I did not change any of the query parameters in both cases. 

**Expected behavior**

I got this message:

```json
{
  "parameters": {
    "analysis_id": "dependency-monkey-210315174958-8ab5cea6bf634915"
  },
  "status": {
    "finished_at": "2021-03-15T17:49:59Z",
    "reason": null,
    "started_at": "2021-03-15T17:49:59Z",
    "state": "failed"
  }
}
```
on what I think is a valid request. Log or report is not avaible.

**Additional context**
I am pretty sure these inspections were working fine about a week ago.

**Comment by harshad16** [comment]
working on it

**Comment by harshad16** [comment]
There were some component configuration missing , please try it again , let me know here if you face any issue.

**Comment by TomasJani** [comment]
I tried a few inspections and it seems to work.

**Comment by fridex** [comment]
> I tried a few inspections and it seems to work.

Thanks for the check and report 👍🏻 

/close
