### ISSUE TITLE
Management API UI on stage unresponsive when retrieving existing dependency monkey report

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/management-api#882]
**Describe the bug**
It looks like an error related to an existing dependency monkey report being unavailable is not properly handled by the API.

**To Reproduce**
1. Go to the management api UI for stage environment
2. Submit a request for `analysis_id` `dependency-monkey-220408080500-9927e6936fbe2f6e` at the `/dependency-monkey/python/{analysis_id}/report` endpoint
3. See the unresponsive page

However, the request is providing the report when posted via curl: 

```
curl -X 'GET'   'https://management.stage.thoth-station.ninja/api/v1/dependency-monkey/python/dependency-monkey-220408080500-9927e6936fbe2f6e/report'  -H 'accept: application/json'
```

**Expected behavior**
Dependency monkey report is returned.

**Comment by fridex** [comment]
Most likely, this might be a limitation of UI (we have observed this already). The swagger UI is not able to return large JSON files. Using cURL might be the recommended way for large JSON responses.

**Comment by mayaCostantini** [comment]
I see, thanks 👍🏻 Closing the issue as I don't think we can do much about it.
/close
