### ISSUE TITLE
Internal Server error when trying to register an index

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/management-api#900]
**Describe the bug**

When trying to register an index via the `/python/package-index/register` endpoint, an internal server error occurs: 

```
{
  "details": {
    "datetime": "2022-07-05T09:10:51.734806",
    "type": "InternalServerError"
  },
  "error": "Internal server error occurred, please contact administrator with provided details."
}
```

Environments: prod (moc), stage and test

**To Reproduce**
1. Go to management-api (any deployment)
2. Try to register the `https://download.pytorch.org/whl/cu113` index:
```
{
  "only_if_package_seen": false,
  "url": "https://download.pytorch.org/whl/cu113",
  "verify_ssl": true
}
```
with `enabled` set to `true`
3. See the error

**Expected behavior**

Index is registered in Thoth's DB.

**Comment by harshad16** [comment]
The changes are now live.
If the warehouse URL is not provided, the API throws an error.
![Screenshot from 2022-10-13 16-09-10](https://user-images.githubusercontent.com/14028058/195699200-d58718bd-cf18-4dc0-aa20-4f0c20192cce.png)

Thanks, everyone for working on this.
closing the issue.
