### ISSUE TITLE
Empty response body for `/python/package-index/register` endpoint

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/management-api#912]
**Describe the bug**

Environment: prod
Empty response body with status code 201 when trying to register the index https://download.pytorch.org/whl/cu113 on the `/python/package-index/register` endpoint.

**To Reproduce**
Go to https://management.prod.thoth-station.ninja/api/v1/ui/#/Python%20Package%20Index/post_register_python_package_index and try to register https://download.pytorch.org/whl/cu113.

**Expected behavior**

Index is registered in Thoth's database.

**Comment by mayaCostantini** [comment]
Related to https://github.com/thoth-station/adviser/issues/2318

**Comment by mayaCostantini** [comment]
Update: the endpoint now returns a 500 error. The management-api version is still at 0.18.4 vs 0.18.5 for the newest release: https://github.com/thoth-station/thoth-application/blob/915ee779471b99da5cd5ac17cb4741e96456fe5f/management-api/overlays/moc-prod/imagestreamtag.yaml#L10.
This might be caused by an issue deploying this version.

cc @harshad16

**Comment by harshad16** [comment]
Thank for the response
Even with updated management-api
the response body is empty 

Version:
```
x-management-api-service-version: 0.18.5+storage.0.72.1.common.0.36.2 
x-management-api-version: 0.18.5 
```

/triage accepted

**Comment by harshad16** [comment]
The changes are now live.
Executed the registry of new index.
The URL index is now registered correctly.
![Screenshot from 2022-10-13 16-06-15](https://user-images.githubusercontent.com/14028058/195698692-e970704a-98ad-42e0-af01-a253022d0af8.png)

Thank you everyone for working on this.
closing this issue.
