### ISSUE TITLE
500 Error when checking for logs of pending solver

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/management-api#920]
**Describe the bug**

Environment: stage

Checking for logs of a pending solver job gives an `InternalServerError`:

```
{
  "details": {
    "datetime": "2022-09-13T12:41:39.258229",
    "type": "InternalServerError"
  },
  "error": "Internal server error occurred, please contact administrator with provided details."
}
```

When solver status is pending:

```
{
  "parameters": {
    "analysis_id": "solver-rhel-8-py38-220913123942-1a7a720b5e604db4"
  },
  "status": {
    "finished_at": null,
    "reason": null,
    "started_at": null,
    "state": "pending"
  }
}
```

**To Reproduce**

Go to the stage instance of Management API and try to solve a package, then check for solver logs when status is `pending`.
Package used to observe this error was:

```
{
  "package_name": "fext",
  "version_specifier": "*"
}
```

from `https://pypi.org/simple`.

**Expected behavior**
This should be handled as a 400 error.

**Comment by harshad16** [comment]
The change is now live on cluster.

A request for a solver is in a pending state.
![Screenshot from 2022-10-13 16-00-27](https://user-images.githubusercontent.com/14028058/195697837-2f4a9d45-2abf-469c-9118-bc3a25a7b8fc.png)

Log request, correctly show 404 not found with details.
![Screenshot from 2022-10-13 16-00-27](https://user-images.githubusercontent.com/14028058/195697940-4689e726-def6-4a74-9c7b-c2cf8b490acd.png)


closing the issue.
Please re-open if faced with same issue.
